export const POLL_ADVICE_FULFILLED = 'POLL_ADVICE_FULFILLED';
export const POLL_ADVICE_START = 'POLL_ADVICE_START';
export const POLL_ADVICE_STOP = 'POLL_ADVICE_STOP';
export const UPDATE_FREQUENCY = 'UPDATE_FREQUENCY';
export const UPDATE_FREQUENCY_FULFILLED = 'UPDATE_FREQUENCY_FULFILLED';