export const GET_DATA = 'GET_DATA';
export const GET_DATA_FULFILLED = 'GET_DATA_FULFILLED';
export const POLL_ADVICE_FULFILLED = 'POLL_ADVICE_FULFILLED';
export const POLL_ADVICE_START = 'POLL_ADVICE_START';
export const POLL_ADVICE_STOP = 'POLL_ADVICE_STOP';
export const UPDATE_COUNT = 'UPDATE_COUNT';
export const UPDATE_COUNT_FULFILLED = 'UPDATE_COUNT_FULFILLED';